name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip==20.2.4 poetry==1.1.4
        poetry config virtualenvs.create false
        poetry install
    - name: Check formatting
      run: black --check ./
    - name: Check typings
      run: mypy *.py
    - name: Test with pytest
      run: pytest ./
